apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend-v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      service: frontend
      version: v1
  template:
    metadata:
      labels:
        service: frontend
        api: external
        version: v1   
    spec:
      containers:
      - image: vschau/udacity-frontend:local
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
      restartPolicy: Always

