apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      service: reverseproxy
      version: v2
  template:
    metadata:
      labels:
        service: reverseproxy
        version: v2
    spec:
      containers:
      - image: vschau/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"       
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - cat
            - ./etc/nginx/nginx.conf
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1  
      restartPolicy: Always
